server:
  port: 8081

spring:
  application:
    name: ms-solicitudes
  datasource:
    url: jdbc:postgresql://localhost:5432/REEMPLAZAR_DB
    username: REEMPLAZAR_USUARIO
    password: REEMPLAZAR_PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
